let PRECIOUNITARIO = 30.0
let CANTIDAD = 8.0
let DESCUENTO = 15.0

let SUBTOTAL = PRECIOUNITARIO * CANTIDAD
let MONTODESCUENTO = SUBTOTAL * DESCUENTO / 100.0
let PAGOTOTAL = SUBTOTAL - MONTODESCUENTO

print("SUBTOTAL: \(SUBTOTAL)")
print("MONTO DEL DESCUENTO: \(MONTODESCUENTO)")
print( "PAGO TOTAL: \(PAGOTOTAL)")
